apiVersion: apps/v1
kind: Deployment
metadata:
  name: exhibition-fe-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exhibition-fe
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: exhibition-fe
    spec:
      containers:
      - image: scgskku/exhibition-fe
        imagePullPolicy: Always
        name: exhibition-fe
        ports:
        - containerPort: 3000