apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-be
resources:
- ../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: exhibition-fe-ingress
images:
- name: scgskku/exhibition-fe
  newTag: df