apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exhibition-be
resources:
- namespace.yaml
- secret.yaml
- ../../base/be


patches:
- path: domain.json
  target:
    kind: Ingress
    name: exhibition-be-ingress
images:
- name: scgskku/exhibition-be
  newTag: 5292a695b4da86aa60a8f9cbdd88797e10175921
